baseURL = "https://strongaya.github.io/AYA-cancer-data-schema/"
theme = "hugo-book"
title = "STRONG AYA Codebook"
enableGitInfo = true

[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1

[menu]
[[menu.after]]
name = "About STRONG AYA"
url = "https://strongaya.eu"
weight = 10

[[menu.after]]
name = "STRONG AYA GitHub"
url = "https://github.com/STRONGAYA"
weight = 20

[[menu.after]]
name = "Associated scientific publication (in preparation)"
url = ""
weight = 40

[params]
BookTheme = 'auto'
BookToC = false
BookFavicon = 'favicon.ico'
BookSection = 'AYA-cancer-data-schema'
BookDateFormat = 'January 2, 2006'

# Used for 'Last Modified' and 'Edit this page' links.
BookRepo = 'https://github.com/STRONGAYA/AYA-cancer-data-schema'